# Weighted centroid 
**the “centre of mass” of the ERPAC map**
- Where is the ERPAC activity centred overall?

In [50]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from scipy.stats import ttest_ind, t
from mne.stats import permutation_cluster_test

import os
import sys
from pathlib import Path
PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(PROJECT_ROOT))
from config.paths import ERPAC_DIR, ROI_STCS_DIR
from config.config import COUPLINGS, TASK_STAGES, ROI, TOI, GROUPS, SUBJECTS

%matplotlib qt

In [51]:
SUBJECTS

{'Y': ['s1_pac_sub01',
  's1_pac_sub07',
  's1_pac_sub10',
  's1_pac_sub11',
  's1_pac_sub22',
  's1_pac_sub24',
  's1_pac_sub26',
  's1_pac_sub29',
  's1_pac_sub32',
  's1_pac_sub33',
  's1_pac_sub38',
  's1_pac_sub43',
  's1_pac_sub52',
  's1_pac_sub58',
  's1_pac_sub59',
  's1_pac_sub61',
  's1_pac_sub63',
  's1_pac_sub64',
  's1_pac_sub66',
  's1_pac_sub67',
  's1_pac_sub71',
  's1_pac_sub76',
  's1_pac_sub77'],
 'O': ['s1_pac_sub12',
  's1_pac_sub14',
  's1_pac_sub15',
  's1_pac_sub17',
  's1_pac_sub20',
  's1_pac_sub21',
  's1_pac_sub23',
  's1_pac_sub34',
  's1_pac_sub35',
  's1_pac_sub36',
  's1_pac_sub40',
  's1_pac_sub41',
  's1_pac_sub45',
  's1_pac_sub47',
  's1_pac_sub48',
  's1_pac_sub49',
  's1_pac_sub50',
  's1_pac_sub53',
  's1_pac_sub54',
  's1_pac_sub55',
  's1_pac_sub56',
  's1_pac_sub60',
  's1_pac_sub62',
  's1_pac_sub68']}

In [52]:
# ============================================================
# 1. LOAD TIME-RESOLVED ERPAC DATA
# ============================================================

erpac_df = pd.read_parquet(
    os.path.join(
        ERPAC_DIR,
        "erpac_results.parquet"
    )
)

erpac_df_toi = erpac_df[
    (
        (erpac_df["task_stage"] == "plan") &
        erpac_df["time"].between(
            TOI["plan"]["start"],
            TOI["plan"]["end"]
        )
    )
    |
    (
        (erpac_df["task_stage"] == "go") &
        erpac_df["time"].between(
            TOI["go"]["start"],
            TOI["go"]["end"]
        )
    )
].copy()

erpac_df_toi

,sub,group,task,task_stage,coupling,roi,amp_freq,time,erpac_value
176,s1_pac_sub12,O,FTT,go,alpha_gamma,M1,32.5,-0.148,0.129945
177,s1_pac_sub12,O,FTT,go,alpha_gamma,M1,32.5,-0.146,0.131710
178,s1_pac_sub12,O,FTT,go,alpha_gamma,M1,32.5,-0.144,0.133261
179,s1_pac_sub12,O,FTT,go,alpha_gamma,M1,32.5,-0.142,0.134622
180,s1_pac_sub12,O,FTT,go,alpha_gamma,M1,32.5,-0.140,0.136041
...,...,...,...,...,...,...,...,...,...
25430755,s1_pac_sub77,Y,FTT,plan,theta_gamma,SMA,76.5,0.492,0.153508
25430756,s1_pac_sub77,Y,FTT,plan,theta_gamma,SMA,76.5,0.494,0.151223
25430757,s1_pac_sub77,Y,FTT,plan,theta_gamma,SMA,76.5,0.496,0.145920
25430758,s1_pac_sub77,Y,FTT,plan,theta_gamma,SMA,76.5,0.498,0.146189
25430759,s1_pac_sub77,Y,FTT,plan,theta_gamma,SMA,76.5,0.500,0.139976

In [53]:
# Extract one participant's ERPAC map

def get_subject_erpac_map(
    erpac_df,
    sub,
    group,
    coupling,
    task_stage,
    roi,
    task="FTT",
):
    df = erpac_df[
        (erpac_df["sub"] == sub) &
        (erpac_df["group"] == group) &
        (erpac_df["task"] == task) &
        (erpac_df["coupling"] == coupling) &
        (erpac_df["task_stage"] == task_stage) &
        (erpac_df["roi"] == roi)
    ].copy()

    pivot = df.pivot(
        index="amp_freq",
        columns="time",
        values="erpac_value",
    )

    pivot = pivot.sort_index(
        axis=0
    ).sort_index(
        axis=1
    )

    freqs = pivot.index.to_numpy(
        dtype=float
    )

    times = pivot.columns.to_numpy(
        dtype=float
    )

    erpac_map = pivot.to_numpy()

    return erpac_map, freqs, times



# ============================================================
# Weighted centroid
# ===========================================================

def erpac_centroid(
    erpac_map,
    freqs,
    times,
    top_percent=20,
):
    """
    Weighted centroid of strongest ERPAC values.

    Parameters
    ----------
    erpac_map : ndarray
        Shape (n_freqs, n_times).

    freqs : ndarray
        Gamma frequencies.

    times : ndarray
        Time points.

    top_percent : float or None
        Percentage of strongest ERPAC bins to retain.
        Example:
            20 = top 20%
            None = use whole map

    Returns
    -------
    centroid_time
    centroid_freq
    """
    
    x = erpac_map.copy()

    # Remove invalid values
    x[~np.isfinite(x)] = np.nan

    if np.all(np.isnan(x)):
        return np.nan, np.nan

    # ----------------------------------------
    # Restrict to strongest ERPAC values
    # ----------------------------------------

    if top_percent is not None:
        percentile = 100 - top_percent

        threshold = np.nanpercentile(
            x,
            percentile
        )

        weights = np.where(
            x >= threshold,
            x,
            0
        )

    else:
        weights = np.nan_to_num(
            x,
            nan=0
        )

    # Ensure non-negative weights
    weights = np.clip(
        weights,
        0,
        None
    )

    total_weight = np.sum(weights)

    if total_weight == 0:
        return np.nan, np.nan

    # ----------------------------------------
    # Coordinates
    # ----------------------------------------

    freq_grid, time_grid = np.meshgrid(
        freqs,
        times,
        indexing="ij"
    )

    centroid_time = (
        np.sum(weights * time_grid)
        / total_weight
    )

    centroid_freq = (
        np.sum(weights * freq_grid)
        / total_weight
    )

    return centroid_time, centroid_freq

In [54]:
sub = "s1_pac_sub01"
group = "Y"
coupling = "theta_gamma"
task_stage = "plan"
roi = "SMA"

erpac_map, freqs, times = get_subject_erpac_map(
    erpac_df_toi,
    sub=sub,
    group=group,
    coupling=coupling,
    task_stage=task_stage,
    roi=roi,
)

centroid_time, centroid_freq = erpac_centroid(
    erpac_map,
    freqs,
    times,
    top_percent=20,
)

print(
    f"centroid time: {centroid_time:.2f} s\ncentroid frequency: {centroid_freq:.2f} Hz"
)

centroid time: 0.23 s
centroid frequency: 50.74 Hz

In [55]:
def calculate_all_centroids(
    erpac_df,
    coupling,
    task_stage,
    roi,
    task="FTT",
    top_percent=20,
):
    rows = []

    df_condition = erpac_df[
        (erpac_df["task"] == task) &
        (erpac_df["coupling"] == coupling) &
        (erpac_df["task_stage"] == task_stage) &
        (erpac_df["roi"] == roi)
    ]

    for group in GROUPS:

        subs = sorted(
            df_condition[
                df_condition["group"] == group
            ]["sub"].unique()
        )

        for sub in subs:

            erpac_map, freqs, times = get_subject_erpac_map(
                erpac_df=erpac_df,
                sub=sub,
                group=group,
                coupling=coupling,
                task_stage=task_stage,
                roi=roi,
                task=task,
            )

            centroid_time, centroid_freq = erpac_centroid(
                erpac_map=erpac_map,
                freqs=freqs,
                times=times,
                top_percent=top_percent,
            )

            rows.append({
                "sub": sub,
                "group": group,
                "coupling": coupling,
                "task_stage": task_stage,
                "roi": roi,
                "centroid_time": centroid_time,
                "centroid_freq": centroid_freq,
            })

    return pd.DataFrame(rows)

In [56]:
centroid_df = calculate_all_centroids(
    erpac_df_toi,
    coupling=coupling,
    task_stage=task_stage,
    roi=roi,
    top_percent=20,
)

In [57]:
centroid_df

,sub,group,coupling,task_stage,roi,centroid_time,centroid_freq
0,s1_pac_sub01,Y,theta_gamma,plan,SMA,0.230121,50.735763
1,s1_pac_sub07,Y,theta_gamma,plan,SMA,0.270223,58.966059
2,s1_pac_sub10,Y,theta_gamma,plan,SMA,0.249846,53.061807
3,s1_pac_sub11,Y,theta_gamma,plan,SMA,0.267594,52.634122
4,s1_pac_sub22,Y,theta_gamma,plan,SMA,0.248820,52.913415
5,s1_pac_sub24,Y,theta_gamma,plan,SMA,0.221219,48.422502
6,s1_pac_sub26,Y,theta_gamma,plan,SMA,0.215091,52.137924
7,s1_pac_sub29,Y,theta_gamma,plan,SMA,0.258308,53.195741
8,s1_pac_sub32,Y,theta_gamma,plan,SMA,0.199400,55.068959
9,s1_pac_sub33,Y,theta_gamma,plan,SMA,0.260254,57.768729
10,s1_pac_sub38,Y,theta_gamma,plan,SMA,0.265582,56.357736
11,s1_pac_sub43,Y,theta_gamma,plan,SMA,0.249650,56.036370
12,s1_pac_sub52,Y,theta_gamma,plan,SMA,0.216922,55.366969
13,s1_pac_sub58,Y,theta_gamma,plan,SMA,0.231098,54.131314
14,s1_pac_sub59,Y,theta_gamma,plan,SMA,0.270392,50.872116
15,s1_pac_sub61,Y,theta_gamma,plan,SMA,0.277533,52.100872
16,s1_pac_sub63,Y,theta_gamma,plan,SMA,0.263484,51.730526
17,s1_pac_sub64,Y,theta_gamma,plan,SMA,0.272417,52.442702
18,s1_pac_sub66,Y,theta_gamma,plan,SMA,0.309799,52.989517
19,s1_pac_sub67,Y,theta_gamma,plan,SMA,0.262771,56.845626
20,s1_pac_sub71,Y,theta_gamma,plan,SMA,0.214022,52.187085
21,s1_pac_sub76,Y,theta_gamma,plan,SMA,0.232396,52.396101
22,s1_pac_sub77,Y,theta_gamma,plan,SMA,0.302534,62.614068
23,s1_pac_sub12,O,theta_gamma,plan,SMA,0.275179,46.497508
24,s1_pac_sub14,O,theta_gamma,plan,SMA,0.228177,50.406562
25,s1_pac_sub15,O,theta_gamma,plan,SMA,0.266379,57.201851
26,s1_pac_sub17,O,theta_gamma,plan,SMA,0.245618,56.014878
27,s1_pac_sub20,O,theta_gamma,plan,SMA,0.234843,50.630006
28,s1_pac_sub21,O,theta_gamma,plan,SMA,0.264097,53.480448
29,s1_pac_sub23,O,theta_gamma,plan,SMA,0.231573,56.840412
30,s1_pac_sub34,O,theta_gamma,plan,SMA,0.199511,54.343364
31,s1_pac_sub35,O,theta_gamma,plan,SMA,0.281075,54.971480
32,s1_pac_sub36,O,theta_gamma,plan,SMA,0.301324,52.488717
33,s1_pac_sub40,O,theta_gamma,plan,SMA,0.266486,50.060105
34,s1_pac_sub41,O,theta_gamma,plan,SMA,0.257910,52.743740
35,s1_pac_sub45,O,theta_gamma,plan,SMA,0.228178,51.574347
36,s1_pac_sub47,O,theta_gamma,plan,SMA,0.215485,55.780984
37,s1_pac_sub48,O,theta_gamma,plan,SMA,0.226114,54.049899
38,s1_pac_sub49,O,theta_gamma,plan,SMA,0.248061,57.485272
39,s1_pac_sub50,O,theta_gamma,plan,SMA,0.225295,60.327403
40,s1_pac_sub53,O,theta_gamma,plan,SMA,0.234553,49.226516
41,s1_pac_sub54,O,theta_gamma,plan,SMA,0.239690,53.364531
42,s1_pac_sub55,O,theta_gamma,plan,SMA,0.286091,53.542538
43,s1_pac_sub56,O,theta_gamma,plan,SMA,0.233823,55.431446
44,s1_pac_sub60,O,theta_gamma,plan,SMA,0.286385,51.981944
45,s1_pac_sub62,O,theta_gamma,plan,SMA,0.218678,52.118048
46,s1_pac_sub68,O,theta_gamma,plan,SMA,0.261022,59.020996

In [60]:
centroid_df.describe()

       centroid_time  centroid_freq
count      47.000000      47.000000
mean        0.249894      53.841681
std         0.026941       3.139991
min         0.199400      46.497508
25%         0.229150      52.109460
50%         0.249650      53.195741
75%         0.267040      55.897931
max         0.309799      62.614068

In [61]:
centroid_df.groupby(["group", "task_stage", "coupling"]).describe()

                             centroid_time                                \
                                     count      mean       std       min
group task_stage coupling
O     plan       theta_gamma          24.0  0.248148  0.026172  0.199511
Y     plan       theta_gamma          23.0  0.251716  0.028191  0.199400

                                                                      \
                                   25%       50%       75%       max
group task_stage coupling
O     plan       theta_gamma  0.228178  0.242654  0.266406  0.301324
Y     plan       theta_gamma  0.230610  0.258308  0.268908  0.309799

                             centroid_freq                                  \
                                     count       mean       std        min
group task_stage coupling
O     plan       theta_gamma          24.0  53.732625  3.240046  46.497508
Y     plan       theta_gamma          23.0  53.955479  3.100617  48.422502


                                    25%        50%        75%        max
group task_stage coupling
O     plan       theta_gamma  51.880045  53.511493  55.839458  60.327403
Y     plan       theta_gamma  52.162505  52.989517  55.701669  62.614068

ALL CONDITIONS

In [62]:
centroid_dfs = []

for coupling in erpac_df_toi["coupling"].unique():

    for task_stage in erpac_df_toi["task_stage"].unique():

        for roi in erpac_df_toi["roi"].unique():

            print(
                f"Processing: "
                f"{coupling} | {task_stage} | {roi}"
            )

            centroid_df = calculate_all_centroids(
                erpac_df_toi,
                coupling=coupling,
                task_stage=task_stage,
                roi=roi,
                top_percent=20,
            )

            # Add condition identifiers if your function
            # does not already include them
            centroid_df["coupling"] = coupling
            centroid_df["task_stage"] = task_stage
            centroid_df["roi"] = roi

            centroid_dfs.append(
                centroid_df
            )


# ============================================================
# COMBINE EVERYTHING
# ============================================================

centroid_df_all = pd.concat(
    centroid_dfs,
    ignore_index=True
)

print(
    centroid_df_all.shape
)

print(
    centroid_df_all.head()
)

Processing: alpha_gamma | go | M1
Processing: alpha_gamma | go | PMC
Processing: alpha_gamma | go | S1
Processing: alpha_gamma | go | SMA
Processing: alpha_gamma | plan | M1
Processing: alpha_gamma | plan | PMC
Processing: alpha_gamma | plan | S1
Processing: alpha_gamma | plan | SMA
Processing: beta_gamma | go | M1
Processing: beta_gamma | go | PMC
Processing: beta_gamma | go | S1
Processing: beta_gamma | go | SMA
Processing: beta_gamma | plan | M1
Processing: beta_gamma | plan | PMC
Processing: beta_gamma | plan | S1
Processing: beta_gamma | plan | SMA
Processing: theta_gamma | go | M1
Processing: theta_gamma | go | PMC
Processing: theta_gamma | go | S1
Processing: theta_gamma | go | SMA
Processing: theta_gamma | plan | M1
Processing: theta_gamma | plan | PMC
Processing: theta_gamma | plan | S1
Processing: theta_gamma | plan | SMA
(1128, 7)
            sub group     coupling task_stage roi  centroid_time  \
0  s1_pac_sub01     Y  alpha_gamma         go  M1       0.166406
1  s1_pac_sub07     Y  alpha_gamma         go  M1       0.209944
2  s1_pac_sub10     Y  alpha_gamma         go  M1       0.129646
3  s1_pac_sub11     Y  alpha_gamma         go  M1       0.214941
4  s1_pac_sub22     Y  alpha_gamma         go  M1       0.231028

   centroid_freq
0      52.003179
1      55.249328
2      54.710464
3      57.631591
4      57.824228

In [63]:
print(
    centroid_df_all.columns
)

print(
    centroid_df_all.groupby(
        [
            "coupling",
            "task_stage",
            "roi",
        ]
    ).size()
)

Index(['sub', 'group', 'coupling', 'task_stage', 'roi', 'centroid_time',
       'centroid_freq'],
      dtype='str')
coupling     task_stage  roi
alpha_gamma  go          M1     47
                         PMC    47
                         S1     47
                         SMA    47
             plan        M1     47
                         PMC    47
                         S1     47
                         SMA    47
beta_gamma   go          M1     47
                         PMC    47
                         S1     47
                         SMA    47
             plan        M1     47
                         PMC    47
                         S1     47
                         SMA    47
theta_gamma  go          M1     47
                         PMC    47
                         S1     47
                         SMA    47
             plan        M1     47
                         PMC    47
                         S1     47
                         SMA    47
dtype: int64

In [ ]:
centroid_df_all.to_csv(os.path.join(
    ERPAC_DIR,
    "erpac_centroids_all_conditions.csv"),
    index=False
)

In [71]:
centroid_df_all.groupby(
    [   "group",
        "coupling",
        "task_stage",
        "roi",
    ]
).describe(    
    ).to_csv(os.path.join(
    ERPAC_DIR,
    "erpac_centroids_describe.csv")
)

In [70]:
centroid_df_all.groupby(
    [   "group",
        "coupling",
        "task_stage",
        "roi",
    ]
).describe()

                                 centroid_time                                \
                                         count      mean       std       min
group coupling    task_stage roi
O     alpha_gamma go         M1           24.0  0.170628  0.043097  0.086756
                             PMC          24.0  0.177874  0.035390  0.116521
                             S1           24.0  0.169927  0.043488  0.081750
                             SMA          24.0  0.162354  0.041804  0.096722
                  plan       M1           24.0  0.236748  0.046041  0.119063
                             PMC          24.0  0.244678  0.034225  0.169655
                             S1           24.0  0.246314  0.039025  0.164611
                             SMA          24.0  0.242971  0.042009  0.144415
      beta_gamma  go         M1           24.0  0.169482  0.029238  0.099810
                             PMC          24.0  0.158363  0.037738  0.073251
                             S1           24.0  0.172190  0.033132  0.081410
                             SMA          24.0  0.177427  0.029556  0.126261
                  plan       M1           24.0  0.256327  0.022964  0.211429
                             PMC          24.0  0.252701  0.025275  0.212344
                             S1           24.0  0.239408  0.031722  0.160351
                             SMA          24.0  0.247437  0.029176  0.210560
      theta_gamma go         M1           24.0  0.164389  0.039581  0.081577
                             PMC          24.0  0.162121  0.041548  0.084019
                             S1           24.0  0.161880  0.027540  0.092567
                             SMA          24.0  0.173043  0.026166  0.116120
                  plan       M1           24.0  0.253738  0.031164  0.202954
                             PMC          24.0  0.246562  0.035948  0.184034
                             S1           24.0  0.251320  0.027590  0.213678
                             SMA          24.0  0.248148  0.026172  0.199511
Y     alpha_gamma go         M1           23.0  0.184337  0.040268  0.095041
                             PMC          23.0  0.186562  0.042232  0.109869
                             S1           23.0  0.176698  0.037521  0.071123
                             SMA          23.0  0.179671  0.041998  0.100188
                  plan       M1           23.0  0.241666  0.039791  0.172915
                             PMC          23.0  0.242840  0.029503  0.195052
                             S1           23.0  0.245329  0.039443  0.174695
                             SMA          23.0  0.239027  0.026397  0.178922
      beta_gamma  go         M1           23.0  0.176459  0.028718  0.124274
                             PMC          23.0  0.170801  0.035216  0.087293
                             S1           23.0  0.167131  0.023827  0.123541
                             SMA          23.0  0.177573  0.029958  0.117128
                  plan       M1           23.0  0.250970  0.027909  0.211713
                             PMC          23.0  0.253778  0.035409  0.172190
                             S1           23.0  0.251010  0.028553  0.194221
                             SMA          23.0  0.257715  0.030817  0.205714
      theta_gamma go         M1           23.0  0.162436  0.034843  0.085850
                             PMC          23.0  0.173300  0.039090  0.110418
                             S1           23.0  0.162302  0.037135  0.111553
                             SMA          23.0  0.170364  0.033496  0.095168
                  plan       M1           23.0  0.250900  0.031303  0.192204
                             PMC          23.0  0.249651  0.024025  0.208771
                             S1           23.0  0.249076  0.041776  0.176169
                             SMA          23.0  0.251716  0.028191  0.199400

                                                                          \
                                       25%       50%       75%       max
group coupling    task_stage roi
O     alpha_gamma go         M1   0.132737  0.172098  0.196383  0.256380
                             PMC  0.161579  0.166940  0.199752  0.255534
                             S1   0.140631  0.162374  0.188481  0.261759
                             SMA  0.128755  0.163936  0.192190  0.248368
                  plan       M1   0.209652  0.236585  0.265239  0.319942
                             PMC  0.225693  0.247242  0.270930  0.311658
                             S1   0.225024  0.244608  0.278541  0.311096
                             SMA  0.215354  0.243014  0.271948  0.327258
      beta_gamma  go         M1   0.163591  0.177261  0.183737  0.227819
                             PMC  0.135003  0.157824  0.180791  0.231471
                             S1   0.157275  0.168894  0.193668  0.230637
                             SMA  0.160192  0.177439  0.197111  0.235675
                  plan       M1   0.239471  0.256728  0.266690  0.301986
                             PMC  0.232105  0.245980  0.273476  0.299874
                             S1   0.225576  0.244731  0.259410  0.290866
                             SMA  0.223359  0.246040  0.265263  0.304461
      theta_gamma go         M1   0.129567  0.173981  0.188456  0.231169
                             PMC  0.128851  0.160995  0.200499  0.232469
                             S1   0.144457  0.171995  0.178723  0.203542
                             SMA  0.159120  0.176944  0.190871  0.217235
                  plan       M1   0.231970  0.250047  0.270421  0.325374
                             PMC  0.222437  0.252682  0.275058  0.299417
                             S1   0.227702  0.248853  0.280574  0.299732
                             SMA  0.228178  0.242654  0.266406  0.301324
Y     alpha_gamma go         M1   0.168409  0.191402  0.215707  0.239084
                             PMC  0.153998  0.187904  0.223120  0.248469
                             S1   0.158416  0.181868  0.207061  0.224971
                             SMA  0.155349  0.186753  0.203563  0.283863
                  plan       M1   0.218642  0.244063  0.261393  0.347255
                             PMC  0.217657  0.241380  0.267797  0.289721
                             S1   0.230464  0.247385  0.256424  0.331913
                             SMA  0.228992  0.237130  0.258389  0.297146
      beta_gamma  go         M1   0.156132  0.181072  0.199488  0.215182
                             PMC  0.149608  0.173607  0.198992  0.222070
                             S1   0.147924  0.162549  0.183481  0.208890
                             SMA  0.162636  0.172661  0.195565  0.250793
                  plan       M1   0.230292  0.242635  0.267522  0.319167
                             PMC  0.233000  0.248946  0.270153  0.333217
                             S1   0.233214  0.254104  0.267176  0.311575
                             SMA  0.235958  0.259209  0.273350  0.316197
      theta_gamma go         M1   0.145885  0.162005  0.194344  0.215152
                             PMC  0.140958  0.174163  0.202500  0.234987
                             S1   0.132360  0.151245  0.184379  0.248734
                             SMA  0.152583  0.170081  0.189012  0.229491
                  plan       M1   0.228639  0.250516  0.272816  0.331632
                             PMC  0.236012  0.250156  0.264091  0.299941
                             S1   0.222465  0.246135  0.265098  0.353122
                             SMA  0.230610  0.258308  0.268908  0.309799

                                 centroid_freq                       \
                                         count       mean       std
group coupling    task_stage roi
O     alpha_gamma go         M1           24.0  54.511218  2.611657
                             PMC          24.0  54.202076  2.149856
                             S1           24.0  53.976716  2.420160
                             SMA          24.0  54.171707  2.405719
                  plan       M1           24.0  54.660470  3.367404
                             PMC          24.0  54.283308  2.980124
                             S1           24.0  54.623491  2.983378
                             SMA          24.0  54.271119  2.323391
      beta_gamma  go         M1           24.0  54.649948  2.385456
                             PMC          24.0  54.056116  1.828971
                             S1           24.0  54.483073  1.643976
                             SMA          24.0  55.144017  2.461796
                  plan       M1           24.0  54.005517  2.978698
                             PMC          24.0  54.144692  2.137925
                             S1           24.0  53.951083  2.901754
                             SMA          24.0  53.764278  2.676940
      theta_gamma go         M1           24.0  55.257925  2.197351
                             PMC          24.0  55.642448  2.361174
                             S1           24.0  54.744945  1.744127
                             SMA          24.0  55.286653  2.465146
                  plan       M1           24.0  55.193083  3.156135
                             PMC          24.0  54.277335  2.737784
                             S1           24.0  54.246736  3.152190
                             SMA          24.0  53.732625  3.240046
Y     alpha_gamma go         M1           23.0  55.304684  3.128718
                             PMC          23.0  54.710694  3.008302
                             S1           23.0  54.500114  2.747943
                             SMA          23.0  54.738230  2.069707
                  plan       M1           23.0  53.316669  2.709374
                             PMC          23.0  53.695243  3.250795
                             S1           23.0  52.966611  1.865751
                             SMA          23.0  53.062036  2.561491
      beta_gamma  go         M1           23.0  54.857009  2.085071
                             PMC          23.0  54.626156  2.063036
                             S1           23.0  54.240556  2.253131
                             SMA          23.0  54.953349  1.827547
                  plan       M1           23.0  55.004792  2.416944
                             PMC          23.0  54.874288  2.494171
                             S1           23.0  54.053707  2.007190
                             SMA          23.0  53.799095  2.430869
      theta_gamma go         M1           23.0  55.255152  2.719348
                             PMC          23.0  54.920724  2.364058
                             S1           23.0  54.932328  2.452335
                             SMA          23.0  53.598909  2.557086
                  plan       M1           23.0  53.872222  2.733962
                             PMC          23.0  54.292623  3.026327
                             S1           23.0  53.999403  2.726905
                             SMA          23.0  53.955479  3.100617

                                                                              \
                                        min        25%        50%        75%
group coupling    task_stage roi
O     alpha_gamma go         M1   50.400354  52.824453  53.904323  55.535538
                             PMC  50.230260  53.199440  54.197779  55.923575
                             S1   48.488860  52.515438  54.251027  55.799272
                             SMA  49.365786  52.637332  53.803430  55.498915
                  plan       M1   47.761047  52.713556  54.142329  57.118914
                             PMC  47.613957  52.752695  54.750327  55.969322
                             S1   46.996713  53.082219  54.637097  56.844839
                             SMA  48.708118  53.445245  54.883753  55.524204
      beta_gamma  go         M1   50.162497  53.144689  54.388799  56.527738
                             PMC  49.798952  53.154113  53.765814  54.821961
                             S1   51.397961  53.628917  54.571984  55.848145
                             SMA  50.808633  52.566390  55.366735  57.029633
                  plan       M1   47.704445  52.036962  54.067705  56.329170
                             PMC  49.964582  53.158724  54.065067  55.387011
                             S1   47.356899  52.210272  54.424365  55.525733
                             SMA  49.227628  51.565778  53.716308  55.987834
      theta_gamma go         M1   50.786005  53.895712  55.213916  56.456283
                             PMC  51.848841  53.493252  56.074514  57.391757
                             S1   50.932059  53.464883  55.229805  55.790495
                             SMA  49.211145  54.069796  55.106394  56.865514
                  plan       M1   48.938125  53.417622  55.465064  57.540603
                             PMC  47.743668  52.642284  54.549419  56.425779
                             S1   48.396206  51.367832  55.406638  56.733463
                             SMA  46.497508  51.880045  53.511493  55.839458
Y     alpha_gamma go         M1   49.470214  52.596999  55.971674  57.069929
                             PMC  49.198121  52.798553  54.862675  56.269324
                             S1   49.413971  52.939180  54.444591  55.516782
                             SMA  51.122460  53.484891  54.558180  55.946023
                  plan       M1   48.540198  51.517391  53.299577  53.951346
                             PMC  47.519666  51.294001  54.524293  55.876648
                             S1   48.716726  52.193536  53.133397  53.964098
                             SMA  49.331450  51.264953  52.393260  53.929289
      beta_gamma  go         M1   50.735008  53.166192  55.092818  56.513807
                             PMC  50.715858  53.666653  54.798451  55.915665
                             S1   48.786919  53.264465  53.939606  55.414896
                             SMA  49.422302  54.014649  55.505482  56.068835
                  plan       M1   51.365180  53.306236  55.438501  56.282218
                             PMC  50.188084  53.447266  54.753709  57.146313
                             S1   49.615329  52.664321  53.804867  55.416264
                             SMA  48.836790  52.336223  53.533644  55.786962
      theta_gamma go         M1   50.468602  53.408614  54.624080  56.360924
                             PMC  50.717463  53.706654  55.050277  56.009827
                             S1   50.300356  53.323692  54.586332  56.488189
                             SMA  49.120613  51.810888  53.459326  56.011002
                  plan       M1   48.769760  51.406142  54.410994  55.675534
                             PMC  47.676832  52.495939  53.761882  55.502731
                             S1   47.208236  52.641724  54.051702  55.727315
                             SMA  48.422502  52.162505  52.989517  55.701669


                                        max
group coupling    task_stage roi
O     alpha_gamma go         M1   60.636148
                             PMC  57.368074
                             S1   57.731240
                             SMA  58.461980
                  plan       M1   62.240922
                             PMC  59.448895
                             S1   59.843815
                             SMA  57.715638
      beta_gamma  go         M1   59.135152
                             PMC  58.300705
                             S1   56.872555
                             SMA  59.856998
                  plan       M1   59.856601
                             PMC  58.804692
                             S1   58.661694
                             SMA  58.091919
      theta_gamma go         M1   60.142753
                             PMC  60.332199
                             S1   57.220421
                             SMA  59.854329
                  plan       M1   60.478786
                             PMC  57.530416
                             S1   58.853238
                             SMA  60.327403
Y     alpha_gamma go         M1   60.926905
                             PMC  62.197911
                             S1   60.795626
                             SMA  59.731262
                  plan       M1   59.031229
                             PMC  58.826539
                             S1   56.484170
                             SMA  58.636954
      beta_gamma  go         M1   58.185793
                             PMC  58.421320
                             S1   58.804806
                             SMA  57.872227
                  plan       M1   61.653024
                             PMC  59.053305
                             S1   57.767856
                             SMA  57.693635
      theta_gamma go         M1   60.655587
                             PMC  60.643129
                             S1   61.843370
                             SMA  58.498571
                  plan       M1   58.763913
                             PMC  59.670940
                             S1   58.488817
                             SMA  62.614068

VIZ

In [86]:
def plot_centroid_scatter(
    centroid_df,
    coupling,
    roi,
):
    df = centroid_df[
        (centroid_df["coupling"] == coupling)
        & (centroid_df["roi"] == roi)
    ].copy()

    fig, ax = plt.subplots(figsize=(7, 5))

    markers = {
        "plan": "o",
        "go": "^",
    }

    for (group, stage), d in df.groupby(
        ["group", "task_stage"]
    ):
        ax.scatter(
            d["centroid_time"],
            d["centroid_freq"],
            marker=markers.get(stage, "o"),
            label=f"{group} – {stage}",
            alpha=0.7,
        )

    ax.set_xlabel("Centroid time (s)")
    ax.set_ylabel("Centroid amplitude frequency (Hz)")

    ax.set_title(
        f"{coupling} | {roi}"
    )
    ax.set_xlim(0, 0.4)
    ax.set_ylim(45, 65)

    ax.legend()
    ax.axvline(0, linewidth=1)

    fig.tight_layout()

    return fig

In [90]:
def plot_centroid_distribution(
    centroid_df,
    variable,
    coupling,
    roi,
):
    df = centroid_df[
        (centroid_df["coupling"] == coupling)
        & (centroid_df["roi"] == roi)
    ].copy()

    conditions = (
        df[
            ["group", "task_stage"]
        ]
        .drop_duplicates()
        .reset_index(drop=True)
    )

    fig, ax = plt.subplots(figsize=(7, 5))

    data = []
    labels = []

    for _, row in conditions.iterrows():

        values = df.loc[
            (df["group"] == row["group"])
            & (
                df["task_stage"]
                == row["task_stage"]
            ),
            variable,
        ].dropna()

        data.append(values)

        labels.append(
            f"{row['group']}\n"
            f"{row['task_stage']}"
        )

    ax.boxplot(
        data,
        tick_labels=labels,
        showfliers=False,
    )

    # individual observations
    for i, values in enumerate(
        data,
        start=1,
    ):
        ax.scatter(
            [i] * len(values),
            values,
            alpha=0.5,
        )

    ylabel = {
        "centroid_time":
            "Centroid time (s)",
        "centroid_freq":
            "Centroid amplitude frequency (Hz)",
    }.get(
        variable,
        variable,
    )

    ax.set_ylabel(ylabel)
    if variable == "centroid_time":
        ax.set_ylim(0, 0.38)
    else:
        ax.set_ylim(45, 65)

    ax.set_title(
        f"{coupling} | {roi}"
    )

    fig.tight_layout()

    return fig

In [ ]:
centroids_save_dir = os.path.join(
    ERPAC_DIR,
    "sample_characteristics",
    "centroids"
)

for coupling in COUPLINGS:

    for roi in ROI:
        
        fig1 = plot_centroid_scatter(
            centroid_df_all,
            coupling=coupling,
            roi=roi
        )

        fig2 = plot_centroid_distribution(
            centroid_df_all,
            variable="centroid_freq", # "centroid_time" or "centroid_freq"
            coupling=coupling,
            roi=roi
        )
        
        fig3 = plot_centroid_distribution(
            centroid_df_all,
            variable="centroid_time", # "centroid_time" or "centroid_freq"
            coupling=coupling,
            roi=roi
        )

        fig1.savefig(
            os.path.join(centroids_save_dir, f"centroid_scatter_{coupling}_{roi}.png"),
            dpi=300
        )

        fig2.savefig(
            os.path.join(centroids_save_dir, f"centroid_freq_{coupling}_{roi}.png"),
            dpi=300
        )

        fig3.savefig(
            os.path.join(centroids_save_dir, f"centroid_time_{coupling}_{roi}.png"),
            dpi=300
        )

C:\Users\a1902989\AppData\Local\Temp\ipykernel_26880\3351223820.py:20: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  fig, ax = plt.subplots(figsize=(7, 5))

In [83]:
print(centroids_save_dir)

F:\# study 2\eeg_data\erpac\sample_characteristics\centroids

In [ ]:
centroid_summary = (
    centroid_df_all
    .groupby(
        [
            "group",
            "coupling",
            "task_stage",
            "roi",
        ]
    )
    .agg(
        n=(
            "sub",
            "nunique",
        ),

        time_mean=(
            "centroid_time",
            "mean",
        ),
        time_sd=(
            "centroid_time",
            "std",
        ),

        freq_mean=(
            "centroid_freq",
            "mean",
        ),
        freq_sd=(
            "centroid_freq",
            "std",
        ),
    )
    .reset_index()
)